runtime: python
env: flex
runtime_config:
  python_version: 3.7
entrypoint: gunicorn -b :$PORT movc.wsgi
beta_settings:
  cloud_sql_instances: mo-vc-322002:asia-northeast3:mo-vc-mysql
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
env_variables:
  production: 1