version: "3"
services:
    db:
        image: postgres:latest
        restart: always
        volumes:
            - ./data/db:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    web:
        build: .
        volumes: 
            - .:/code
        ports:
            - "8080:8080"
        environment: 
            - SECRET_KEY=${SECRET_KEY}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
            - AWS_REGION=${AWS_REGION}
            - AWS_S3_CUSTOM_DOMAIN=${AWS_S3_CUSTOM_DOMAIN}
            - KAKAO_API_KEY=${KAKAO_API_KEY}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        depends_on:
            - db
